# libs:
tensorflow-2.4.1.zip: https://cnbj1.fds.api.xiaomi.com/aibench/third_party/tensorflow-2.4.1.zip
tensorflow-2.4.1.zip_md5_checksum: 3674cf2ace8ccab67ca89726b8b12980
MNN-1.1.1.zip: https://cnbj1.fds.api.xiaomi.com/aibench/third_party/MNN-1.1.1.zip
MNN-1.1.1.zip_md5_checksum: 42c8cb30c0683bd1c6e8c7c8a7a59510
mace-1.0.4.zip: https://cnbj1.fds.api.xiaomi.com/aibench/third_party/mace-1.0.4.zip
mace-1.0.4.zip_md5_checksum: 77c8ac455e1424ec1cd740f3f76ac427

# inputs:
imagenet_less.zip: https://cnbj1-fds.api.xiaomi.net/aibench/inputs/imagenet_less.zip
imagenet_less.zip_md5_checksum: e0f7a6b64ed07a0ed0402d61b79cebe2
